GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/fe4f9998-61d5-4f37-bb0b-c5a6b04be57f

###

POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker"
}